
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-13
owner: ucsb-cs156-f24
repo_name: team01-f24-13
pull_requests: [{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"Steven-RecommendationRequest","number":52,"title":"Add PUT (edit) endpoint for a single record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-f24/team01-f24-13/pull/52"}]
