
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-13
owner: ucsb-cs156-f24
repo_name: team01-f24-13
pull_requests: [{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"anteater10-Articles","number":50,"title":"Add Article entity, repository, and migration file","url":"https://github.com/ucsb-cs156-f24/team01-f24-13/pull/50"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"Shivani-Orgs","number":49,"title":"Creating Organizations Database Table","url":"https://github.com/ucsb-cs156-f24/team01-f24-13/pull/49"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"Emily-UCSBDiningCommonsMenuItem","number":48,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create), Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table, Add PUT (edit) endpoint for a single record in UCSBDiningCommonsMenuItem table, Add DELETE endpoint for a specific record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f24/team01-f24-13/pull/48"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"Steven-RecommendationRequest","number":47,"title":"Created database table for RecommendationRequest, Created RecommendationRequestController, added GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f24/team01-f24-13/pull/47"}]
